### ISSUE TITLE
Character set/name issue

### ISSUE THREAD

**Issue by jshinkle** [timwoj/raidgrpinfo#3]
We have a raider with alt+225 (ß) in his name.  When submitting to the form, it gets converted to SS and fails the API pull from the Armory.

![image](https://cloud.githubusercontent.com/assets/12059059/19349721/8b88e4a2-9122-11e6-9b0c-38d793b2675c.png)

![image](https://cloud.githubusercontent.com/assets/12059059/19349755/bc957592-9122-11e6-881e-ec6f8ec1a207.png)

**Comment by timwoj** [comment]
This is fixed now but won't be deployed until BfA lands because of a bunch of stuff sitting in front of it on `master`.
